import type { FortuneTemplate } from '../types.js';

/** 默认运势模板集合 — 覆盖 5 个 sentiment 等级 */
export const DEFAULT_TEMPLATES: FortuneTemplate[] = [
  // ============ GREAT (大吉) ============
  {
    id: 'great-001',
    sentiment: 'great',
    overview: '五行大和，今日提交必过 Review，PR 秒合！',
    do: ['提交重要 PR', '发布新版本', '重构核心模块', '做技术分享'],
    dont: ['摸鱼', '拖延'],
    tip: '趁运势正旺，把搁置的大任务一口气搞定',
  },
  {
    id: 'great-002',
    sentiment: 'great',
    overview: '今日灵感如泉涌，Bug 见你绕道走。写什么都顺！',
    do: ['攻克技术难题', '设计系统架构', '写复杂算法', '优化性能瓶颈'],
    dont: ['做简单重复劳动', '开无意义的会'],
    tip: '把最有挑战性的任务安排在今天',
  },
  {
    id: 'great-003',
    sentiment: 'great',
    overview: '星象大利编程，键盘之上无往不利。',
    do: ['启动新项目', '搭建脚手架', '学习新框架', '写技术方案'],
    dont: ['删库跑路', '砍功能'],
    tip: '开启那个你酝酿已久的 side project',
  },
  {
    id: 'great-004',
    sentiment: 'great',
    overview: '今日代码如有神助，逻辑清晰如行云流水。',
    do: ['处理复杂逻辑', '写单元测试', '完善文档', '做 Code Review'],
    dont: ['浑水摸鱼', '不写测试'],
    tip: '顺手帮同事 Review 代码，好运会传递',
  },
  {
    id: 'great-005',
    sentiment: 'great',
    overview: '运势满格，连 CI 都不好意思挂你。',
    do: ['合并长期分支', '升级依赖版本', '部署到生产环境', '写集成测试'],
    dont: ['偷懒不测试', '跳过 Review'],
    tip: '今天适合做那些平时不敢做的大动作',
  },

  // ============ GOOD (吉) ============
  {
    id: 'good-001',
    sentiment: 'good',
    overview: '小有吉兆，适合攻克那个拖了三天的 Bug。',
    do: ['修复 Bug', '完善错误处理', '补充测试用例', '整理技术债'],
    dont: ['引入新框架', '大范围重构'],
    tip: '专注手头的事，今天适合收尾',
  },
  {
    id: 'good-002',
    sentiment: 'good',
    overview: '今日运势不错，稳中有进，代码质量杠杠的。',
    do: ['优化代码结构', '添加类型注解', '完善日志', '更新 README'],
    dont: ['仓促发版', '跳过测试'],
    tip: '小步快跑，持续改进',
  },
  {
    id: 'good-003',
    sentiment: 'good',
    overview: '天气晴好，心情愉悦，代码自然也写得流畅。',
    do: ['写业务逻辑', '对接 API', '处理数据', '优化 UI'],
    dont: ['和产品吵架', '硬扛技术债'],
    tip: '遇到问题及时沟通，今天沟通运也不错',
  },
  {
    id: 'good-004',
    sentiment: 'good',
    overview: '运势良好，做事有条理，效率比平时高一截。',
    do: ['写技术文档', '梳理代码逻辑', '做任务拆分', '写周报'],
    dont: ['盲目追新', '一次改太多'],
    tip: '把复杂任务拆小，一个个搞定',
  },
  {
    id: 'good-005',
    sentiment: 'good',
    overview: '今日适合精雕细琢，把代码打磨到极致。',
    do: ['重命名变量', '提取公共方法', '优化导入', '清理注释'],
    dont: ['大刀阔斧重构', '改架构'],
    tip: '细节决定成败，今天注重代码美感',
  },

  // ============ NEUTRAL (平) ============
  {
    id: 'neutral-001',
    sentiment: 'neutral',
    overview: '不功不过，按部就班写 CRUD 就好。',
    do: ['写常规代码', '处理工单', '参加站会', '回复消息'],
    dont: ['做高风险操作', '上线大功能'],
    tip: '平平淡淡才是真，不出错就是赢',
  },
  {
    id: 'neutral-002',
    sentiment: 'neutral',
    overview: '今日运势平稳，不宜大动干戈，宜稳扎稳打。',
    do: ['日常开发', '修小 Bug', '写单测', '整理 TODO'],
    dont: ['重构核心模块', '迁移数据库'],
    tip: '保持节奏，不冒进不懈怠',
  },
  {
    id: 'neutral-003',
    sentiment: 'neutral',
    overview: '今日如同编译中的代码——在跑，但别太期待速度。',
    do: ['处理需求评审', '写接口文档', '做日常巡检', '清理邮箱'],
    dont: ['push --force', '合并冲突代码'],
    tip: '慢即是快，稳住别浪',
  },
  {
    id: 'neutral-004',
    sentiment: 'neutral',
    overview: '中规中矩的一天，适合做中规中矩的事。',
    do: ['维护现有功能', '修复边缘 case', '更新版本号', '写注释'],
    dont: ['尝试黑科技', '改全局配置'],
    tip: '今天不追求惊喜，只追求没有 surprise',
  },
  {
    id: 'neutral-005',
    sentiment: 'neutral',
    overview: '运势如同 200 OK——正常响应，没有彩蛋。',
    do: ['按计划推进', '完成排期任务', '代码自测', '提交日报'],
    dont: ['临时加需求', '调整技术栈'],
    tip: '把今天当作普通的一天来过就好',
  },

  // ============ BAD (凶) ============
  {
    id: 'bad-001',
    sentiment: 'bad',
    overview: '今日宜低调，不宜 git push --force。',
    do: ['读文档', '整理笔记', '做技术调研', '清理桌面'],
    dont: ['部署生产环境', '合并主分支', '删除数据'],
    tip: '少动手多动脑，明天会更好',
  },
  {
    id: 'bad-002',
    sentiment: 'bad',
    overview: '运势欠佳，代码里可能潜伏着看不见的 Bug。',
    do: ['补写测试', '增加日志', '做代码备份', '写应急方案'],
    dont: ['上线新功能', '重构核心逻辑', '删除旧代码'],
    tip: '今天的 Bug 可能要明天才暴露，多留心',
  },
  {
    id: 'bad-003',
    sentiment: 'bad',
    overview: '今日容易出岔子，建议开启「防呆模式」。',
    do: ['Review 自己的代码', '检查配置文件', '确认环境变量', '备份数据'],
    dont: ['发版上线', '迁移数据', '改权限'],
    tip: '三思而后行，commit 之前再检查一遍',
  },
  {
    id: 'bad-004',
    sentiment: 'bad',
    overview: '五行相冲，今日 CI/CD 流水线可能会闹脾气。',
    do: ['修复 pipeline', '检查环境', '看监控面板', '做故障演练'],
    dont: ['改 CI 配置', '升级集群', '调整限流'],
    tip: '遇到问题别急，深呼吸再看日志',
  },
  {
    id: 'bad-005',
    sentiment: 'bad',
    overview: '今日变量命名灵感枯竭，foo bar 满天飞。',
    do: ['阅读优秀源码', '学命名规范', '看设计模式', '刷 LeetCode'],
    dont: ['写核心模块', '设计 API', '定技术方案'],
    tip: '先充电再输出，不急于一时',
  },

  // ============ TERRIBLE (大凶) ============
  {
    id: 'terrible-001',
    sentiment: 'terrible',
    overview: '五行缺运，建议今天只看不写，摸鱼保平安。',
    do: ['摸鱼', '看技术博客', '刷社区', '喝咖啡'],
    dont: ['写代码', '部署', '改配置', '碰生产环境'],
    tip: '活着就好，代码明天再写',
  },
  {
    id: 'terrible-002',
    sentiment: 'terrible',
    overview: '今日 rm -rf 风险极高，请远离终端。',
    do: ['做计划', '画原型', '写 PPT', '团队建设'],
    dont: ['敲命令', 'SSH 服务器', '改数据库', 'force push'],
    tip: '手离键盘，可保一日平安',
  },
  {
    id: 'terrible-003',
    sentiment: 'terrible',
    overview: '今日运势触底反弹……还没弹起来。',
    do: ['请假', '午睡', '散步', '和同事聊天'],
    dont: ['写逻辑代码', '做技术决策', '发版', '面试'],
    tip: '这种日子，摸鱼就是最大的生产力',
  },
  {
    id: 'terrible-004',
    sentiment: 'terrible',
    overview: '所有 Bug 今天都会复活，宛如代码界的万圣节。',
    do: ['记录 Bug', '整理 Backlog', '更新 Jira', '打扫工位'],
    dont: ['修复已知 Bug', '关闭工单', '合代码', '上线'],
    tip: '别修 Bug，它们今天修不好。记下来明天再说',
  },
  {
    id: 'terrible-005',
    sentiment: 'terrible',
    overview: '今日适合思考人生：我为什么要当程序员？',
    do: ['看技术大会视频', '逛 GitHub Trending', '写年度总结', '冥想'],
    dont: ['接新需求', '做任何承诺', '预估工时', '改线上配置'],
    tip: '今天是回顾初心的好日子，别写代码了',
  },
];
