import { describe, it, expect } from 'vitest';
import { analyzeWuXing, getRelation, calculateDistribution, evaluateStrength } from '../src/wuxing/analyzer.js';
import { getGanZhi } from '../src/ganzhi/calculator.js';
import { WuXing, WuXingRelation, WuXingStrength } from '../src/types.js';

describe('wuxing/analyzer', () => {
  describe('getRelation', () => {
    it('same element returns Same', () => {
      expect(getRelation(WuXing.Mu, WuXing.Mu)).toBe(WuXingRelation.Same);
    });

    it('wood generates fire', () => {
      expect(getRelation(WuXing.Mu, WuXing.Huo)).toBe(WuXingRelation.Generates);
    });

    it('fire is generated by wood', () => {
      expect(getRelation(WuXing.Huo, WuXing.Mu)).toBe(WuXingRelation.GeneratedBy);
    });

    it('wood overcomes earth', () => {
      expect(getRelation(WuXing.Mu, WuXing.Tu)).toBe(WuXingRelation.Overcomes);
    });

    it('earth is overcome by wood', () => {
      expect(getRelation(WuXing.Tu, WuXing.Mu)).toBe(WuXingRelation.OvercomeBy);
    });
  });

  describe('calculateDistribution', () => {
    it('returns non-negative counts for all elements', () => {
      const ganzhi = getGanZhi(new Date(2024, 2, 15));
      const dist = calculateDistribution(ganzhi);

      for (const element of [WuXing.Mu, WuXing.Huo, WuXing.Tu, WuXing.Jin, WuXing.Shui]) {
        expect(dist[element]).toBeGreaterThanOrEqual(0);
      }
    });

    it('total count should be positive', () => {
      const ganzhi = getGanZhi(new Date(2024, 2, 15));
      const dist = calculateDistribution(ganzhi);
      const total = Object.values(dist).reduce((a, b) => a + b, 0);
      expect(total).toBeGreaterThan(0);
    });
  });

  describe('evaluateStrength', () => {
    it('returns strength for all elements', () => {
      const ganzhi = getGanZhi(new Date(2024, 2, 15));
      const dist = calculateDistribution(ganzhi);
      const str = evaluateStrength(dist, new Date(2024, 2, 15));

      for (const element of [WuXing.Mu, WuXing.Huo, WuXing.Tu, WuXing.Jin, WuXing.Shui]) {
        expect(str[element]).toBeGreaterThanOrEqual(WuXingStrength.VeryWeak);
        expect(str[element]).toBeLessThanOrEqual(WuXingStrength.VeryStrong);
      }
    });
  });

  describe('analyzeWuXing', () => {
    it('returns complete analysis', () => {
      const ganzhi = getGanZhi(new Date(2024, 2, 15));
      const result = analyzeWuXing(ganzhi);

      expect(result.dominant).toBeDefined();
      expect(result.distribution).toBeDefined();
      expect(result.strength).toBeDefined();
      expect(result.strongest).toBeDefined();
      expect(result.weakest).toBeDefined();
      expect(typeof result.isBalanced).toBe('boolean');
      expect(Array.isArray(result.missing)).toBe(true);
      expect(result.luckyElement).toBeDefined();
    });

    it('dominant is the day master wuxing', () => {
      const ganzhi = getGanZhi(new Date(2024, 2, 15));
      const result = analyzeWuXing(ganzhi);
      expect(result.dominant).toBe(ganzhi.day.tianGan.wuxing);
    });
  });
});
